### ISSUE TITLE
Possible ACE Update error?

### ISSUE THREAD

**Issue by FrostySigh** [tacticalrealism/etr_ranks#5]
Not entire sure if this is a ETR Ranks issue of ACE issue but since the last ace update I've been getting this error when loading into a mission but only when ETR Ranks is loaded as a mod.

```

15:50:54   Error position: <getVariable _targetFaction;

           >
15:50:54   Error getvariable: Type HashMap, expected Namespace,Object,Group,Display (dialog),Control,Team member,Task,Location
15:50:54 File /addons/functions/functions/fnc_drawNameTagIcon.sqf..., line 45
15:50:54 Error in expression <omRankIcons = ace_nametags_factionRanks getVariable _targetFaction;
```

**Comment by JasperRab** [comment]
Hello FrostySigh,

Thanks for reporting the issue.
The issue should be fixed, if you could test it that would be amazing.

If the issue persists don't hesitate to report back!

**Comment by FrostySigh** [comment]
Looks like the update fixed it; thanks for a quick fix!
